// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace mvvmMenuSystem {
    using mvvmMenuSystem;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.MVVM;
    using uFrame.MVVM.ViewModels;
    using UniRx;
    using UnityEngine;
    
    
    public class MenuSystemLoaderBase : uFrame.Kernel.SystemLoader {
        
        private MenuRootViewModel _MenuRoot;
        
        private PanelController _PanelController;
        
        private MenuRootController _MenuRootController;
        
        private MainMenuController _MainMenuController;
        
        private ShieldController _ShieldController;
        
        [uFrame.IOC.InjectAttribute("MenuRoot")]
        public virtual MenuRootViewModel MenuRoot {
            get {
                if (this._MenuRoot == null) {
                    this._MenuRoot = this.CreateViewModel<MenuRootViewModel>( "MenuRoot");
                }
                return _MenuRoot;
            }
        }
        
        [uFrame.IOC.InjectAttribute()]
        public virtual PanelController PanelController {
            get {
                if (_PanelController==null) {
                    _PanelController = Container.CreateInstance(typeof(PanelController)) as PanelController;;
                }
                return _PanelController;
            }
            set {
                _PanelController = value;
            }
        }
        
        [uFrame.IOC.InjectAttribute()]
        public virtual MenuRootController MenuRootController {
            get {
                if (_MenuRootController==null) {
                    _MenuRootController = Container.CreateInstance(typeof(MenuRootController)) as MenuRootController;;
                }
                return _MenuRootController;
            }
            set {
                _MenuRootController = value;
            }
        }
        
        [uFrame.IOC.InjectAttribute()]
        public virtual MainMenuController MainMenuController {
            get {
                if (_MainMenuController==null) {
                    _MainMenuController = Container.CreateInstance(typeof(MainMenuController)) as MainMenuController;;
                }
                return _MainMenuController;
            }
            set {
                _MainMenuController = value;
            }
        }
        
        [uFrame.IOC.InjectAttribute()]
        public virtual ShieldController ShieldController {
            get {
                if (_ShieldController==null) {
                    _ShieldController = Container.CreateInstance(typeof(ShieldController)) as ShieldController;;
                }
                return _ShieldController;
            }
            set {
                _ShieldController = value;
            }
        }
        
        public override void Load() {
            Container.RegisterViewModelManager<PanelViewModel>(new ViewModelManager<PanelViewModel>());
            Container.RegisterController<PanelController>(PanelController);
            Container.RegisterViewModelManager<MenuRootViewModel>(new ViewModelManager<MenuRootViewModel>());
            Container.RegisterController<MenuRootController>(MenuRootController);
            Container.RegisterViewModelManager<MainMenuViewModel>(new ViewModelManager<MainMenuViewModel>());
            Container.RegisterController<MainMenuController>(MainMenuController);
            Container.RegisterViewModelManager<ShieldViewModel>(new ViewModelManager<ShieldViewModel>());
            Container.RegisterController<ShieldController>(ShieldController);
            Container.RegisterViewModel<MenuRootViewModel>(MenuRoot, "MenuRoot");
        }
    }
}
