// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace mvvmMenuSystem {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.Kernel.Serialization;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.MVVM.Services;
    using uFrame.MVVM.ViewModels;
    using UniRx;
    using UnityEngine;
    
    
    public class PanelViewBase : uFrame.MVVM.Views.ViewBase {
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public Single _depthIndex;
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public String _panelName;
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public Boolean _isCache;
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public BGM _BGMType;
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public String _CurrentBGM;
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public Boolean _isActive;
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public String _BGMName;
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public Int32 _posIndex;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("PlayPanelAnimation")]
        [UnityEngine.HideInInspector()]
        public bool _BindPlayPanelAnimation = true;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("DestroyPanel")]
        [UnityEngine.HideInInspector()]
        public bool _BindDestroyPanel = true;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("HidePanel")]
        [UnityEngine.HideInInspector()]
        public bool _BindHidePanel = true;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("ShowPanel")]
        [UnityEngine.HideInInspector()]
        public bool _BindShowPanel = true;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("posIndex")]
        [UnityEngine.HideInInspector()]
        public bool _BindposIndex = true;
        
        [uFrame.MVVM.Attributes.UFGroup("posIndex")]
        [UnityEngine.SerializeField()]
        [UnityEngine.HideInInspector()]
        [UnityEngine.Serialization.FormerlySerializedAsAttribute("_posIndexonlyWhenChanged")]
        protected bool _posIndexOnlyWhenChanged;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("FocusPanel")]
        [UnityEngine.HideInInspector()]
        public bool _BindFocusPanel = true;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("isActive")]
        [UnityEngine.HideInInspector()]
        public bool _BindisActive = true;
        
        [uFrame.MVVM.Attributes.UFGroup("isActive")]
        [UnityEngine.SerializeField()]
        [UnityEngine.HideInInspector()]
        [UnityEngine.Serialization.FormerlySerializedAsAttribute("_isActiveonlyWhenChanged")]
        protected bool _isActiveOnlyWhenChanged;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("SetPanelData")]
        [UnityEngine.HideInInspector()]
        public bool _BindSetPanelData = true;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("depthIndex")]
        [UnityEngine.HideInInspector()]
        public bool _BinddepthIndex = true;
        
        [uFrame.MVVM.Attributes.UFGroup("depthIndex")]
        [UnityEngine.SerializeField()]
        [UnityEngine.HideInInspector()]
        [UnityEngine.Serialization.FormerlySerializedAsAttribute("_depthIndexonlyWhenChanged")]
        protected bool _depthIndexOnlyWhenChanged;
        
        public override string DefaultIdentifier {
            get {
                return base.DefaultIdentifier;
            }
        }
        
        public override System.Type ViewModelType {
            get {
                return typeof(PanelViewModel);
            }
        }
        
        public PanelViewModel Panel {
            get {
                return (PanelViewModel)ViewModelObject;
            }
        }
        
        protected override void InitializeViewModel(uFrame.MVVM.ViewModels.ViewModel model) {
            base.InitializeViewModel(model);
            // NOTE: this method is only invoked if the 'Initialize ViewModel' is checked in the inspector.
            // var vm = model as PanelViewModel;
            // This method is invoked when applying the data from the inspector to the viewmodel.  Add any view-specific customizations here.
            var panelview = ((PanelViewModel)model);
            panelview.depthIndex = this._depthIndex;
            panelview.panelName = this._panelName;
            panelview.isCache = this._isCache;
            panelview.BGMType = this._BGMType;
            panelview.CurrentBGM = this._CurrentBGM;
            panelview.isActive = this._isActive;
            panelview.BGMName = this._BGMName;
            panelview.posIndex = this._posIndex;
        }
        
        public override void Bind() {
            base.Bind();
            // Use this.Panel to access the viewmodel.
            // Use this method to subscribe to the view-model.
            // Any designer bindings are created in the base implementation.
            if (_BindPlayPanelAnimation) {
                this.BindCommandExecuted(this.Panel.PlayPanelAnimation, this.PlayPanelAnimationExecuted);
            }
            if (_BindDestroyPanel) {
                this.BindCommandExecuted(this.Panel.DestroyPanel, this.DestroyPanelExecuted);
            }
            if (_BindHidePanel) {
                this.BindCommandExecuted(this.Panel.HidePanel, this.HidePanelExecuted);
            }
            if (_BindShowPanel) {
                this.BindCommandExecuted(this.Panel.ShowPanel, this.ShowPanelExecuted);
            }
            if (_BindposIndex) {
                this.BindProperty(this.Panel.posIndexProperty, this.posIndexChanged, _posIndexOnlyWhenChanged);
            }
            if (_BindFocusPanel) {
                this.BindCommandExecuted(this.Panel.FocusPanel, this.FocusPanelExecuted);
            }
            if (_BindisActive) {
                this.BindProperty(this.Panel.isActiveProperty, this.isActiveChanged, _isActiveOnlyWhenChanged);
            }
            if (_BindSetPanelData) {
                this.BindCommandExecuted(this.Panel.SetPanelData, this.SetPanelDataExecuted);
            }
            if (_BinddepthIndex) {
                this.BindProperty(this.Panel.depthIndexProperty, this.depthIndexChanged, _depthIndexOnlyWhenChanged);
            }
        }
        
        public virtual void PlayPanelAnimationExecuted(PlayPanelAnimationCommand command) {
        }
        
        public virtual void DestroyPanelExecuted(DestroyPanelCommand command) {
        }
        
        public virtual void HidePanelExecuted(HidePanelCommand command) {
        }
        
        public virtual void ShowPanelExecuted(ShowPanelCommand command) {
        }
        
        public virtual void posIndexChanged(Int32 arg1) {
        }
        
        public virtual void FocusPanelExecuted(FocusPanelCommand command) {
        }
        
        public virtual void isActiveChanged(Boolean arg1) {
        }
        
        public virtual void SetPanelDataExecuted(SetPanelDataCommand command) {
        }
        
        public virtual void depthIndexChanged(Single arg1) {
        }
        
        public virtual void ExecuteFocusPanel(FocusPanelCommand command) {
            command.Sender = Panel;
            Panel.FocusPanel.OnNext(command);
        }
        
        public virtual void ExecuteHidePanel(HidePanelCommand command) {
            command.Sender = Panel;
            Panel.HidePanel.OnNext(command);
        }
        
        public virtual void ExecuteShowPanel(ShowPanelCommand command) {
            command.Sender = Panel;
            Panel.ShowPanel.OnNext(command);
        }
        
        public virtual void ExecuteSetPanelData(SetPanelDataCommand command) {
            command.Sender = Panel;
            Panel.SetPanelData.OnNext(command);
        }
        
        public virtual void ExecutePlayPanelAnimation(PlayPanelAnimationCommand command) {
            command.Sender = Panel;
            Panel.PlayPanelAnimation.OnNext(command);
        }
        
        public virtual void ExecuteDestroyPanel(DestroyPanelCommand command) {
            command.Sender = Panel;
            Panel.DestroyPanel.OnNext(command);
        }
    }
}
