// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace mvvmMenuSystem {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.Kernel.Serialization;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.MVVM.Services;
    using uFrame.MVVM.ViewModels;
    using UniRx;
    using UnityEngine;
    
    
    public class ShieldViewBase : PanelView {
        
        [UnityEngine.SerializeField()]
        [uFrame.MVVM.Attributes.UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public Color _color;
        
        [uFrame.MVVM.Attributes.UFToggleGroup("color")]
        [UnityEngine.HideInInspector()]
        public bool _Bindcolor = true;
        
        [uFrame.MVVM.Attributes.UFGroup("color")]
        [UnityEngine.SerializeField()]
        [UnityEngine.HideInInspector()]
        [UnityEngine.Serialization.FormerlySerializedAsAttribute("_coloronlyWhenChanged")]
        protected bool _colorOnlyWhenChanged;
        
        public override string DefaultIdentifier {
            get {
                return base.DefaultIdentifier;
            }
        }
        
        public override System.Type ViewModelType {
            get {
                return typeof(ShieldViewModel);
            }
        }
        
        public ShieldViewModel Shield {
            get {
                return (ShieldViewModel)ViewModelObject;
            }
        }
        
        protected override void InitializeViewModel(uFrame.MVVM.ViewModels.ViewModel model) {
            base.InitializeViewModel(model);
            // NOTE: this method is only invoked if the 'Initialize ViewModel' is checked in the inspector.
            // var vm = model as ShieldViewModel;
            // This method is invoked when applying the data from the inspector to the viewmodel.  Add any view-specific customizations here.
            var shieldview = ((ShieldViewModel)model);
            shieldview.color = this._color;
        }
        
        public override void Bind() {
            base.Bind();
            // Use this.Shield to access the viewmodel.
            // Use this method to subscribe to the view-model.
            // Any designer bindings are created in the base implementation.
            if (_Bindcolor) {
                this.BindProperty(this.Shield.colorProperty, this.colorChanged, _colorOnlyWhenChanged);
            }
        }
        
        public virtual void colorChanged(Color arg1) {
        }
    }
}
