// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace mvvmMenuSystem {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class MainMenuControllerBase : PanelController {
        
        private uFrame.MVVM.ViewModels.IViewModelManager _MainMenuViewModelManager;
        
        [uFrame.IOC.InjectAttribute("MainMenu")]
        public uFrame.MVVM.ViewModels.IViewModelManager MainMenuViewModelManager {
            get {
                return _MainMenuViewModelManager;
            }
            set {
                _MainMenuViewModelManager = value;
            }
        }
        
        public IEnumerable<MainMenuViewModel> MainMenuViewModels {
            get {
                return MainMenuViewModelManager.OfType<MainMenuViewModel>();
            }
        }
        
        public override void Setup() {
            base.Setup();
            // This is called when the controller is created
        }
        
        public override void Initialize(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.Initialize(viewModel);
            // This is called when a viewmodel is created
            this.InitializeMainMenu(((MainMenuViewModel)(viewModel)));
        }
        
        public virtual MainMenuViewModel CreateMainMenu() {
            return ((MainMenuViewModel)(this.Create(Guid.NewGuid().ToString())));
        }
        
        public override uFrame.MVVM.ViewModels.ViewModel CreateEmpty() {
            return new MainMenuViewModel(this.EventAggregator);
        }
        
        public virtual void InitializeMainMenu(MainMenuViewModel viewModel) {
            // This is called when a MainMenuViewModel is created
            MainMenuViewModelManager.Add(viewModel);
        }
        
        public override void DisposingViewModel(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.DisposingViewModel(viewModel);
            MainMenuViewModelManager.Remove(viewModel);
        }
    }
}
