// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace mvvmMenuSystem {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class MenuRootControllerBase : uFrame.MVVM.Controller {
        
        private uFrame.MVVM.ViewModels.IViewModelManager _MenuRootViewModelManager;
        
        private MenuRootViewModel _MenuRoot;
        
        [uFrame.IOC.InjectAttribute("MenuRoot")]
        public uFrame.MVVM.ViewModels.IViewModelManager MenuRootViewModelManager {
            get {
                return _MenuRootViewModelManager;
            }
            set {
                _MenuRootViewModelManager = value;
            }
        }
        
        [uFrame.IOC.InjectAttribute("MenuRoot")]
        public MenuRootViewModel MenuRoot {
            get {
                return _MenuRoot;
            }
            set {
                _MenuRoot = value;
            }
        }
        
        public IEnumerable<MenuRootViewModel> MenuRootViewModels {
            get {
                return MenuRootViewModelManager.OfType<MenuRootViewModel>();
            }
        }
        
        public override void Setup() {
            base.Setup();
            // This is called when the controller is created
        }
        
        public override void Initialize(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.Initialize(viewModel);
            // This is called when a viewmodel is created
            this.InitializeMenuRoot(((MenuRootViewModel)(viewModel)));
        }
        
        public virtual MenuRootViewModel CreateMenuRoot() {
            return ((MenuRootViewModel)(this.Create(Guid.NewGuid().ToString())));
        }
        
        public override uFrame.MVVM.ViewModels.ViewModel CreateEmpty() {
            return new MenuRootViewModel(this.EventAggregator);
        }
        
        public virtual void InitializeMenuRoot(MenuRootViewModel viewModel) {
            // This is called when a MenuRootViewModel is created
            viewModel.LoadPanel.Action = this.LoadPanelHandler;
            MenuRootViewModelManager.Add(viewModel);
        }
        
        public override void DisposingViewModel(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.DisposingViewModel(viewModel);
            MenuRootViewModelManager.Remove(viewModel);
        }
        
        public virtual void LoadPanelHandler(LoadPanelCommand command) {
            this.LoadPanel(command.Sender as MenuRootViewModel, command);
        }
        
        public virtual void LoadPanel(MenuRootViewModel viewModel, LoadPanelCommand arg) {
        }
    }
}
