// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace mvvmMenuSystem {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    
    
    public class ShieldControllerBase : PanelController {
        
        private uFrame.MVVM.ViewModels.IViewModelManager _ShieldViewModelManager;
        
        [uFrame.IOC.InjectAttribute("Shield")]
        public uFrame.MVVM.ViewModels.IViewModelManager ShieldViewModelManager {
            get {
                return _ShieldViewModelManager;
            }
            set {
                _ShieldViewModelManager = value;
            }
        }
        
        public IEnumerable<ShieldViewModel> ShieldViewModels {
            get {
                return ShieldViewModelManager.OfType<ShieldViewModel>();
            }
        }
        
        public override void Setup() {
            base.Setup();
            // This is called when the controller is created
        }
        
        public override void Initialize(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.Initialize(viewModel);
            // This is called when a viewmodel is created
            this.InitializeShield(((ShieldViewModel)(viewModel)));
        }
        
        public virtual ShieldViewModel CreateShield() {
            return ((ShieldViewModel)(this.Create(Guid.NewGuid().ToString())));
        }
        
        public override uFrame.MVVM.ViewModels.ViewModel CreateEmpty() {
            return new ShieldViewModel(this.EventAggregator);
        }
        
        public virtual void InitializeShield(ShieldViewModel viewModel) {
            // This is called when a ShieldViewModel is created
            ShieldViewModelManager.Add(viewModel);
        }
        
        public override void DisposingViewModel(uFrame.MVVM.ViewModels.ViewModel viewModel) {
            base.DisposingViewModel(viewModel);
            ShieldViewModelManager.Remove(viewModel);
        }
    }
}
