// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace mvvmMenuSystem {
    using mvvmMenuSystem;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.Kernel.Serialization;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.MVVM.ViewModels;
    using UnityEngine;
    
    
    public partial class LoadPanelCommand : uFrame.MVVM.ViewModels.ViewModelCommand {
        
        private String _panelName;
        
        public String panelName {
            get {
                return _panelName;
            }
            set {
                _panelName = value;
            }
        }
    }
    
    public partial class FocusPanelCommand : uFrame.MVVM.ViewModels.ViewModelCommand {
        
        private Boolean _isFocus;
        
        public Boolean isFocus {
            get {
                return _isFocus;
            }
            set {
                _isFocus = value;
            }
        }
    }
    
    public partial class SetPanelDataCommand : uFrame.MVVM.ViewModels.ViewModelCommand {
        
        private object _panelData;
        
        public object panelData {
            get {
                return _panelData;
            }
            set {
                _panelData = value;
            }
        }
    }
    
    public partial class PlayPanelAnimationCommand : uFrame.MVVM.ViewModels.ViewModelCommand {
        
        private AnimType _panelAnimType;
        
        public AnimType panelAnimType {
            get {
                return _panelAnimType;
            }
            set {
                _panelAnimType = value;
            }
        }
    }
    
    public partial class HidePanelCommand : uFrame.MVVM.ViewModels.ViewModelCommand {
    }
    
    public partial class ShowPanelCommand : uFrame.MVVM.ViewModels.ViewModelCommand {
    }
    
    public partial class DestroyPanelCommand : uFrame.MVVM.ViewModels.ViewModelCommand {
    }
}
